SET IDENTITY_INSERT [dbo].[Parameters] ON
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (1, N'Standard', 0, 4, 64, 12)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (2, N'Plus', 80, 4, 128, 12)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (3, N'Premium', 200, 6, 256, 12)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (4, N'Standard', 0, 6, 128, 13)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (5, N'Plus', 100, 6, 256, 13)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (6, N'Premium', 300, 8, 512, 13)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (7, N'Standard', 0, 4, 32, 14)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (8, N'Plus', 80, 4, 64, 14)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (9, N'Premium', 120, 4, 128, 14)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (10, N'Standard', 0, 6, 256, 15)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (11, N'Standard', 0, 8, 512, 16)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (12, N'Standard', 0, 6, 256, 17)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (13, N'Premium', 170, 12, 512, 17)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (14, N'Standard', 0, 12, 512, 18)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (15, N'Standard', 0, 4, 64, 19)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (16, N'Premium', 70, 6, 128, 19)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (17, N'Standard', 0, 8, 256, 20)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (18, N'Premium', 300, 12, 512, 20)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (19, N'Standard', 0, 4, 64, 21)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (20, N'Plus', 80, 6, 128, 21)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (21, N'Standard', 0, 8, 256, 22)
INSERT INTO [dbo].[Parameters] ([Id], [Name], [HalfPrice], [Ram], [Rom], [TypeId]) VALUES (22, N'Premium', 300, 12, 512, 22)
SET IDENTITY_INSERT [dbo].[Parameters] OFF
