// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.Addbrands")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.AddTypes")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.AddParameters")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.Removebrands")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.RemoveTypes")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.RemoveParameters")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.Updatebrands")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.UpdateTypes")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.UpdateParameters")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.FindTypeByBrandName")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.NoHalfPriceByBrandname")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.NoHalfPriceByBrandnameAsync")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.FindParameterByTypeName")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.FindParameterByTypeNameAsync")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.doSomething")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.doSomethingAsync")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.Addbrands")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.AddTypes")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.AddParameters")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.Removebrands")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.RemoveTypes")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.RemoveParameters")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.Updatebrands")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.UpdateTypes")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.UpdateParameters")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.DoSomething")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.DoSomethingAsync")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.Addbrands")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.AddTypes")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.AddParameters")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.Removebrands")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.RemoveTypes")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.RemoveParameters")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.Updatebrands")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.UpdateTypes")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.UpdateParameters")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.ListallBrands")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.ListallParameters")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.ListallTypes")]
[assembly: SuppressMessage("", "CA1014", Justification = "<NikGitStats>", Scope = "module")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.BrandyTypesCount")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.BrandyTypesCount")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.BrandsRating")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.BrandsRating")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.SumHalfPrice")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.SumHalfPrice")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.BrandRateById")]
[assembly: SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "<Approved>", Scope = "type", Target = "~T:SmartPhoneShop.Program.Factory")]
[assembly: SuppressMessage("Design", "CA1024:Use properties where appropriate", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Factory.GetLog~SmartPhoneShop.Logic.Blogic")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.ErrorChecker(System.String)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.ErrorChecker(System.String)~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.ErrorMessage")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.BrandIdChecker(System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.TypeIdChecker(System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.ParameterIdChecker(System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.BrandRateByName")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.AllHalfPrice")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.AllRamAndRomByTypeName")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Program.Program.SumRamAndRomByTypeNameAsync")]
