// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.Blogic.DoSomething(System.String)~System.Collections.Generic.IList{System.Object}")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.Blogic.DoSomething(System.String)~System.Collections.Generic.IList{System.Object}")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Approved>", Scope = "member", Target = "~F:SmartPhoneShop.Logic.Blogic.repok")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Approved>", Scope = "member", Target = "~F:SmartPhoneShop.Logic.AllRepository.Brands")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<Approved>", Scope = "member", Target = "~F:SmartPhoneShop.Logic.AllRepository.Brands")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Approved>", Scope = "member", Target = "~F:SmartPhoneShop.Logic.AllRepository.Types")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<Approved>", Scope = "member", Target = "~F:SmartPhoneShop.Logic.AllRepository.Types")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Approved>", Scope = "member", Target = "~F:SmartPhoneShop.Logic.AllRepository.Parameters")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<Approved>", Scope = "member", Target = "~F:SmartPhoneShop.Logic.AllRepository.Parameters")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1614:Element parameter documentation should have text", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.AllRepository.#ctor(SmartPhoneShop.Repository.BrandRepository,SmartPhoneShop.Repository.TypesRepository,SmartPhoneShop.Repository.ParametersRepository)")]
[assembly: SuppressMessage("", "CA1014", Justification = "<NikGitStats>", Scope = "module")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.Blogic.DoSomething(System.String)~System.Collections.Generic.IList{SmartPhoneShop.Logic.NonCrudObjects.DoSomethhingObject}")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.Blogic.DoSomething(System.String)~System.Collections.Generic.IList{SmartPhoneShop.Logic.NonCrudObjects.DoSomethhingObject}")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.NonCrudObjects.BrandRating.#ctor(System.Int32,System.Double)")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.NonCrudObjects.DoSomethhingObject.#ctor(System.String,System.String,System.Int32)")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.NonCrudObjects.NonCrudParameter.#ctor(System.Int32,System.String,System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Repository.NonCrudObjects.NonCrudType.#ctor(System.Int32,System.Int32,System.String,System.Int32,System.Int32)")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.NonCrudObjects.BrandRating.#ctor(System.String,System.Double)")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.NonCrudObjects.AllhalfPrice.#ctor(System.String,System.Double)")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.Blogic.FindParameterByTypeName2(System.String)~System.Collections.Generic.IList{SmartPhoneShop.Logic.NonCrudObjects.NonCrudParameter}")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.Blogic.NoHalfPriceByTypename(System.String)~System.Collections.Generic.IList{SmartPhoneShop.Logic.NonCrudObjects.NonCrudParameter}")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.Blogic.SumRamAndRomByType(System.String)~System.Collections.Generic.IList{SmartPhoneShop.Logic.NonCrudObjects.SumRamAndRom}")]
[assembly: SuppressMessage("Globalization", "CA1309:Use ordinal string comparison", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.Blogic.SumRamAndRomByType(System.String)~System.Collections.Generic.IList{SmartPhoneShop.Logic.NonCrudObjects.SumRamAndRom}")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.Blogic.SumRamAndRomByType(System.String)~System.Collections.Generic.IList{SmartPhoneShop.Logic.NonCrudObjects.SumRamAndRom}")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Approved>", Scope = "member", Target = "~M:SmartPhoneShop.Logic.NonCrudObjects.SumRamAndRom.#ctor(System.String,System.Double,System.Double)")]
